---
- hosts: localhost
  become: yes
  pre_tasks:

    - name: Create run user
      ansible.builtin.user:
        name: "{{ user }}"
        comment: "custom user for running idr related tasks."
        shell: /bin/bash
        update_password: always
        password: "{{ user_pwd | password_hash('sha512')}}"
        state: present
        

  tasks:
    - name: Create application's home directory.
      become: yes
      become_user: "{{ user }}"
      file:
        path: "{{idr_home_dir}}" 
        state: directory
        owner: "{{ user }}"
        mode: 0755  

    - name: Create logs directory.
      become: yes
      become_user: "{{ user }}"
      file:
        path: "{{ idr_home_dir }}/logs"
        state: directory
        owner: "{{ user }}"
        

    - name: Download the config template.
      get_url:
        url: "{{ config_template }}"
        dest: "{{ idr_home_dir }}/config.yaml"
        owner: "{{ user }}"
        
    - name: Copy runner script to idr home dir. 
      copy:
        src: ./run.sh
        dest: "{{ idr_home_dir }}"
        owner: "{{ user }}"
        mode: 0755


    - name: Get latest idr_client binaries download url.
      uri:
        url: "{{ release_url }}"
        return_content: yes
        body_format: json
      register: idr_release
      until: idr_release.status == 200
      retries: 5


    - name: Download client binaries in executable mode.
      get_url:
        url: "{{ idr_release.json.assets[0]['browser_download_url'] }}"
        dest: "{{ idr_home_dir }}/client"
        mode: 0755
        owner: "{{ user }}"
        force: yes


    - name: Create a cron task for the user 
      ansible.builtin.cron:
        name: run auto extraction
        user: "{{ user }}"
        hour: "3"
        minute: "0"
        job: "{{ idr_home_dir }}/run.sh"
        