---
- hosts: localhost
  connection: local
  become: yes
  pre_tasks:

    - name: Add our application user to the system.
      ansible.builtin.user:
        name: "{{ user }}"
        comment: "Custom user for running idr related tasks."
        shell: /bin/bash
        update_password: always
        password: "{{ user_pwd | password_hash('sha512')}}"
        state: present

    
  tasks:
    - name: Create application's home directory.
      become: yes
      become_user: "{{ user }}"
      file:
        path: "{{idr_home_dir}}" 
        state: directory
        owner: "{{ user }}"
        mode: 0755  


    - name: Create logs directory.
      become: yes
      become_user: "{{ user }}"
      file:
        path: "{{ idr_home_dir }}/logs"
        state: directory
        owner: "{{ user }}"
        

    - name: Copy the configuration file to app home directory
      ansible.builtin.template:
        src: app.config.j2
        dest: "{{ idr_home_dir }}/config.yaml"
        owner: "{{ user }}"
        

    - name: Copy script for running the client to idr home dir. 
      copy:
        src: ./run.sh
        dest: "{{ idr_home_dir }}"
        owner: "{{ user }}"
        mode: 0755


    - name: Get the url for downloading the latest idr_client binaries.
      uri:
        url: "{{ release_url }}"
        return_content: yes
        body_format: json
      register: idr_release
      until: idr_release.status == 200
      retries: 5


    - name: Download client binaries in executable mode.
      get_url:
        url: "{{ idr_release.json.assets[0]['browser_download_url'] }}"
        dest: "{{ idr_home_dir }}/client"
        owner: "{{ user }}"
        mode: 0755
        force: yes


    - name: Create a cron task to run the extraction every day at 3am, 9am and 3pm
      ansible.builtin.cron:
        name: run auto extraction
        user: "{{ user }}"
        hour: "3,9,15"
        minute: "0"
        job: "{{ idr_home_dir }}/run.sh"
        
